Vagrant.configure("2") do |config|

  # config.vm.synced_folder "../applications", "/applications", create: true

  config.vm.define "postgres" do |postgres|
    config.vm.provider "docker" do |d|
      d.build_dir = "./postgres"
    end
  end

  config.vm.define "phoenix" do |phoenix|
    config.vm.provider "docker" do |d|
      d.build_dir = "./phoenix"
    end
  end
end
